export  const countries = [
  {
    name: "Afghanistan",
    code: "AF",
    dialCode: "+93",
    flag: "https://flagcdn.com/w40/af.png",
  },
  {
    name: "Albania",
    code: "AL",
    dialCode: "+355",
    flag: "https://flagcdn.com/w40/al.png",
  },
  {
    name: "Algeria",
    code: "DZ",
    dialCode: "+213",
    flag: "https://flagcdn.com/w40/dz.png",
  },
  {
    name: "Andorra",
    code: "AD",
    dialCode: "+376",
    flag: "https://flagcdn.com/w40/ad.png",
  },
  {
    name: "Angola",
    code: "AO",
    dialCode: "+244",
    flag: "https://flagcdn.com/w40/ao.png",
  },
  {
    name: "Argentina",
    code: "AR",
    dialCode: "+54",
    flag: "https://flagcdn.com/w40/ar.png",
  },
  {
    name: "Armenia",
    code: "AM",
    dialCode: "+374",
    flag: "https://flagcdn.com/w40/am.png",
  },
  {
    name: "Australia",
    code: "AU",
    dialCode: "+61",
    flag: "https://flagcdn.com/w40/au.png",
  },
  {
    name: "Austria",
    code: "AT",
    dialCode: "+43",
    flag: "https://flagcdn.com/w40/at.png",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    dialCode: "+994",
    flag: "https://flagcdn.com/w40/az.png",
  },
  {
    name: "Bahamas",
    code: "BS",
    dialCode: "+1-242",
    flag: "https://flagcdn.com/w40/bs.png",
  },
  {
    name: "Bahrain",
    code: "BH",
    dialCode: "+973",
    flag: "https://flagcdn.com/w40/bh.png",
  },
  {
    name: "Bangladesh",
    code: "BD",
    dialCode: "+880",
    flag: "https://flagcdn.com/w40/bd.png",
  },
  {
    name: "Belarus",
    code: "BY",
    dialCode: "+375",
    flag: "https://flagcdn.com/w40/by.png",
  },
  {
    name: "Belgium",
    code: "BE",
    dialCode: "+32",
    flag: "https://flagcdn.com/w40/be.png",
  },
  {
    name: "Belize",
    code: "BZ",
    dialCode: "+501",
    flag: "https://flagcdn.com/w40/bz.png",
  },
  {
    name: "Benin",
    code: "BJ",
    dialCode: "+229",
    flag: "https://flagcdn.com/w40/bj.png",
  },
  {
    name: "Bhutan",
    code: "BT",
    dialCode: "+975",
    flag: "https://flagcdn.com/w40/bt.png",
  },
  {
    name: "Bolivia",
    code: "BO",
    dialCode: "+591",
    flag: "https://flagcdn.com/w40/bo.png",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    dialCode: "+387",
    flag: "https://flagcdn.com/w40/ba.png",
  },
  {
    name: "Botswana",
    code: "BW",
    dialCode: "+267",
    flag: "https://flagcdn.com/w40/bw.png",
  },
  {
    name: "Brazil",
    code: "BR",
    dialCode: "+55",
    flag: "https://flagcdn.com/w40/br.png",
  },
  {
    name: "Brunei",
    code: "BN",
    dialCode: "+673",
    flag: "https://flagcdn.com/w40/bn.png",
  },
  {
    name: "Bulgaria",
    code: "BG",
    dialCode: "+359",
    flag: "https://flagcdn.com/w40/bg.png",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    dialCode: "+226",
    flag: "https://flagcdn.com/w40/bf.png",
  },
  {
    name: "Burundi",
    code: "BI",
    dialCode: "+257",
    flag: "https://flagcdn.com/w40/bi.png",
  },
  {
    name: "Cambodia",
    code: "KH",
    dialCode: "+855",
    flag: "https://flagcdn.com/w40/kh.png",
  },
  {
    name: "Cameroon",
    code: "CM",
    dialCode: "+237",
    flag: "https://flagcdn.com/w40/cm.png",
  },
  {
    name: "Canada",
    code: "CA",
    dialCode: "+1",
    flag: "https://flagcdn.com/w40/ca.png",
  },
  {
    name: "Chile",
    code: "CL",
    dialCode: "+56",
    flag: "https://flagcdn.com/w40/cl.png",
  },
  {
    name: "China",
    code: "CN",
    dialCode: "+86",
    flag: "https://flagcdn.com/w40/cn.png",
  },
  {
    name: "Colombia",
    code: "CO",
    dialCode: "+57",
    flag: "https://flagcdn.com/w40/co.png",
  },
  {
    name: "Costa Rica",
    code: "CR",
    dialCode: "+506",
    flag: "https://flagcdn.com/w40/cr.png",
  },
  {
    name: "Croatia",
    code: "HR",
    dialCode: "+385",
    flag: "https://flagcdn.com/w40/hr.png",
  },
  {
    name: "Cuba",
    code: "CU",
    dialCode: "+53",
    flag: "https://flagcdn.com/w40/cu.png",
  },
  {
    name: "Cyprus",
    code: "CY",
    dialCode: "+357",
    flag: "https://flagcdn.com/w40/cy.png",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    dialCode: "+420",
    flag: "https://flagcdn.com/w40/cz.png",
  },
  {
    name: "Denmark",
    code: "DK",
    dialCode: "+45",
    flag: "https://flagcdn.com/w40/dk.png",
  },
  {
    name: "Egypt",
    code: "EG",
    dialCode: "+20",
    flag: "https://flagcdn.com/w40/eg.png",
  },
  {
    name: "Finland",
    code: "FI",
    dialCode: "+358",
    flag: "https://flagcdn.com/w40/fi.png",
  },
  {
    name: "France",
    code: "FR",
    dialCode: "+33",
    flag: "https://flagcdn.com/w40/fr.png",
  },
  {
    name: "Germany",
    code: "DE",
    dialCode: "+49",
    flag: "https://flagcdn.com/w40/de.png",
  },
  {
    name: "Greece",
    code: "GR",
    dialCode: "+30",
    flag: "https://flagcdn.com/w40/gr.png",
  },
  {
    name: "Hong Kong",
    code: "HK",
    dialCode: "+852",
    flag: "https://flagcdn.com/w40/hk.png",
  },
  {
    name: "Hungary",
    code: "HU",
    dialCode: "+36",
    flag: "https://flagcdn.com/w40/hu.png",
  },
  {
    name: "Iceland",
    code: "IS",
    dialCode: "+354",
    flag: "https://flagcdn.com/w40/is.png",
  },
  {
    name: "India",
    code: "IN",
    dialCode: "+91",
    flag: "https://flagcdn.com/w40/in.png",
  },
  {
    name: "Indonesia",
    code: "ID",
    dialCode: "+62",
    flag: "https://flagcdn.com/w40/id.png",
  },
  {
    name: "Iran",
    code: "IR",
    dialCode: "+98",
    flag: "https://flagcdn.com/w40/ir.png",
  },
  {
    name: "Iraq",
    code: "IQ",
    dialCode: "+964",
    flag: "https://flagcdn.com/w40/iq.png",
  },
  {
    name: "Ireland",
    code: "IE",
    dialCode: "+353",
    flag: "https://flagcdn.com/w40/ie.png",
  },
  {
    name: "Israel",
    code: "IL",
    dialCode: "+972",
    flag: "https://flagcdn.com/w40/il.png",
  },
  {
    name: "Italy",
    code: "IT",
    dialCode: "+39",
    flag: "https://flagcdn.com/w40/it.png",
  },
  {
    name: "Japan",
    code: "JP",
    dialCode: "+81",
    flag: "https://flagcdn.com/w40/jp.png",
  },
  {
    name: "Kenya",
    code: "KE",
    dialCode: "+254",
    flag: "https://flagcdn.com/w40/ke.png",
  },
  {
    name: "South Korea",
    code: "KR",
    dialCode: "+82",
    flag: "https://flagcdn.com/w40/kr.png",
  },
  {
    name: "Malaysia",
    code: "MY",
    dialCode: "+60",
    flag: "https://flagcdn.com/w40/my.png",
  },
  {
    name: "Mexico",
    code: "MX",
    dialCode: "+52",
    flag: "https://flagcdn.com/w40/mx.png",
  },
  {
    name: "Nepal",
    code: "NP",
    dialCode: "+977",
    flag: "https://flagcdn.com/w40/np.png",
  },
  {
    name: "Netherlands",
    code: "NL",
    dialCode: "+31",
    flag: "https://flagcdn.com/w40/nl.png",
  },
  {
    name: "New Zealand",
    code: "NZ",
    dialCode: "+64",
    flag: "https://flagcdn.com/w40/nz.png",
  },
  {
    name: "Nigeria",
    code: "NG",
    dialCode: "+234",
    flag: "https://flagcdn.com/w40/ng.png",
  },
  {
    name: "Norway",
    code: "NO",
    dialCode: "+47",
    flag: "https://flagcdn.com/w40/no.png",
  },
  {
    name: "Pakistan",
    code: "PK",
    dialCode: "+92",
    flag: "https://flagcdn.com/w40/pk.png",
  },
  {
    name: "Philippines",
    code: "PH",
    dialCode: "+63",
    flag: "https://flagcdn.com/w40/ph.png",
  },
  {
    name: "Poland",
    code: "PL",
    dialCode: "+48",
    flag: "https://flagcdn.com/w40/pl.png",
  },
  {
    name: "Portugal",
    code: "PT",
    dialCode: "+351",
    flag: "https://flagcdn.com/w40/pt.png",
  },
  {
    name: "Qatar",
    code: "QA",
    dialCode: "+974",
    flag: "https://flagcdn.com/w40/qa.png",
  },
  {
    name: "Russia",
    code: "RU",
    dialCode: "+7",
    flag: "https://flagcdn.com/w40/ru.png",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    dialCode: "+966",
    flag: "https://flagcdn.com/w40/sa.png",
  },
  {
    name: "Singapore",
    code: "SG",
    dialCode: "+65",
    flag: "https://flagcdn.com/w40/sg.png",
  },
  {
    name: "South Africa",
    code: "ZA",
    dialCode: "+27",
    flag: "https://flagcdn.com/w40/za.png",
  },
  {
    name: "Spain",
    code: "ES",
    dialCode: "+34",
    flag: "https://flagcdn.com/w40/es.png",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    dialCode: "+94",
    flag: "https://flagcdn.com/w40/lk.png",
  },
  {
    name: "Sweden",
    code: "SE",
    dialCode: "+46",
    flag: "https://flagcdn.com/w40/se.png",
  },
  {
    name: "Switzerland",
    code: "CH",
    dialCode: "+41",
    flag: "https://flagcdn.com/w40/ch.png",
  },
  {
    name: "Thailand",
    code: "TH",
    dialCode: "+66",
    flag: "https://flagcdn.com/w40/th.png",
  },
  {
    name: "Turkey",
    code: "TR",
    dialCode: "+90",
    flag: "https://flagcdn.com/w40/tr.png",
  },
  {
    name: "Ukraine",
    code: "UA",
    dialCode: "+380",
    flag: "https://flagcdn.com/w40/ua.png",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    dialCode: "+971",
    flag: "https://flagcdn.com/w40/ae.png",
  },
  {
    name: "United Kingdom",
    code: "GB",
    dialCode: "+44",
    flag: "https://flagcdn.com/w40/gb.png",
  },
  {
    name: "United States",
    code: "US",
    dialCode: "+1",
    flag: "https://flagcdn.com/w40/us.png",
  },
  {
    name: "Vietnam",
    code: "VN",
    dialCode: "+84",
    flag: "https://flagcdn.com/w40/vn.png",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    dialCode: "+263",
    flag: "https://flagcdn.com/w40/zw.png",
  },
];
export default countries;